import { GetStaticProps } from 'next'
import Head from 'next/head'

import { PageLayout } from '@/layouts/PageLayout'
import { personalInfoStore } from '@/store/personalInfo'
import { projectsStore } from '@/store/projects'
import { PersonalInfo } from '@/types/personal-info'
import { Project } from '@/types/project'
import { getPersonalInfo } from '@/utils/getPersonalInfo'
import { getProjects } from '@/utils/getProjects'
import { useHydrateAtoms } from 'jotai/utils'

export default function Home({
	projects,
	personalInfo
}: {
	projects: Project[]
	personalInfo: PersonalInfo
}) {
	// eslint-disable-next-line @typescript-eslint/ban-ts-comment
	// @ts-ignore
	useHydrateAtoms([[projectsStore, projects]])

	// eslint-disable-next-line @typescript-eslint/ban-ts-comment
	// @ts-ignore
	useHydrateAtoms([[personalInfoStore, personalInfo]])

	return (
		<>
			<Head>
				<title>Christian | Portfólio</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<PageLayout />
		</>
	)
}

export const getStaticProps: GetStaticProps = async () => {
	const projects = await getProjects()

	const personalInfo = await getPersonalInfo()

	return {
		props: { projects, personalInfo }
	}
}
