import useTranslation from 'next-translate/useTranslation'
import { Inter } from 'next/font/google'
import Head from 'next/head'

import LocaleSwitcher from '@/components/buttons/LocaleSwitcher'

import { Center } from '@chakra-ui/react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
	const { t, lang } = useTranslation('common')
	const count = t('count', { count: 42 })
	const title = t('title')

	console.log(lang)

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Center fontFamily={inter.style.fontFamily} h="100vh">
				<p>{count}</p>
				<p>{title}</p>

				<LocaleSwitcher />
			</Center>
		</>
	)
}
